import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Navbar } from './components/Navbar';
import Container from '@mui/material/Container';
import { Player } from './components/Player';
import { AppProvider } from './store/provider/Provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Spoty page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <Navbar />
          <Container style={{ margin: '90px 0' }}>
            {children}
          </Container>
          <Player />
        </AppProvider>
      </body>
    </html>
  )
}
